name: CI

on:
  push:
    branches:
      - main
      - develop
      - "feature/**"

  pull_request:
    branches:
      - main
      - develop

jobs:
  validar:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Verificar estructura del proyecto
        run: |
          test -f README.md
          test -d Documentos
          test -d Documentos/Requisitos
          test -d .github/workflows

      - name: Verificar requerimientos funcionales
        run: |
          test -f "Documentos/Requisitos/RF1-gestión-usuarios.md"
          test -f "Documentos/Requisitos/RF2-gestión-pacientes.md"
          test -f "Documentos/Requisitos/RF3-gestión-citas.md"
          echo "Requerimientos funcionales encontrados correctamente"

      - name: Verificar archivo del pipeline
        run: |
          test -f .github/workflows/ci.yml
          echo "Pipeline configurado correctamente"
